### ISSUE TITLE
konachan站点下载失败

### ISSUE THREAD

**Issue by dornenkrone** [azige/moebooru-viewer#5]
OS：windows 10 pro 
java：版本8 更新121 工作版本 1.8.0——121-b13
软件：moeviewer v0.5.2
yande.re站点正常
konchan站点显示正常下载的时候不读条 直接显示失败。
之前的版本使用的时候konachan站点打开之后不显示图片 均为加载失败
网络状况：  江苏移动教育网  konachan被墙  yande.re正常访问

log信息
[main] INFO io.github.azige.moebooruviewer.MoebooruViewer - init
[pool-2-thread-1] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://yande.re/post.json?api_version=2&include_pools=1&page=1&limit=100&tags=
[pool-2-thread-4] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://assets.yande.re/data/preview/2a/4c/2a4c3c41d456cffe8e120aa83ba91e6e.jpg
[pool-2-thread-3] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://assets.yande.re/data/preview/53/ae/53aea3a1dfd4ef5383bd54cd0d2840a1.jpg
[pool-2-thread-2] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://assets.yande.re/data/preview/bd/df/bddf9c7ed6a4aa5f6828499dbe7e67d5.jpg
[pool-2-thread-4] INFO io.github.azige.moebooruviewer.NetIO - downloaded: yande.re\previews\386617.jpg
[pool-2-thread-3] INFO io.github.azige.moebooruviewer.NetIO - downloaded: yande.re\previews\386618.jpg
[pool-2-thread-2] INFO io.github.azige.moebooruviewer.NetIO - downloaded: yande.re\previews\386619.jpg
[AWT-EventQueue-0] INFO io.github.azige.moebooruviewer.MoebooruViewer - destroy

**Comment by azige** [comment]
似乎还是konachan.net给的URL格式的问题
6a3f9fa462bcb044beb61fdfc196c1bdc7945642 应该暂时修复这个问题了

**Comment by dornenkrone** [comment]
问题已经解决了  谢谢
另外  谢谢你能开发出这么优秀的作品。减轻了收图党的很多烦恼  十分感谢
